name: Build and Publish Base Image
on:
  # Allow for manual run
  workflow_dispatch:

jobs:
  # https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages
  build-base:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build & push image
        run: |
          echo "${{ github.token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          make build
          make push
          echo "💾 Image built." >> $GITHUB_STEP_SUMMARY
